on:
  push:
    tags:
      - '**'

name: Sentry-Release

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get the tag name
        id: tag
        run: echo TAG=${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT
      - name: Create Sentry release
        uses: getsentry/action-release@v2
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          version: foxy-farmer@${{ steps.tag.outputs.TAG }}
